version: '3.8'

services:
  demo_service:
    build: ./
    command: ./demo_service
    ports:
      - 8098:8089
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data:Z
    env_file:
      - .env
    ports:
      - 5436:5432

